### ISSUE TITLE
installation error in db

### ISSUE THREAD

**Issue by rec0d** [PhentomPT/PhentomCMS#10]
after install getting no error, but when press finnish i come to this: http://i.imgur.com/IVnP4xm.png
how to solve this issues?

**Comment by PhentomPT** [comment]
What core are you using, mangos or trinity?

**Comment by rec0d** [comment]
cmangos 2.4.3 with a eluna core

**Comment by rec0d** [comment]
and its a debian host, if it makes any changes.

**Comment by rec0d** [comment]
and when i have login to admin area i get this error: http://i.imgur.com/5MPDfSx.png

**Comment by PhentomPT** [comment]
all those are related to lack of code for the mangos core.
I will try to add some for this cases.

**Comment by rec0d** [comment]
thanks, so it will work for trinitycore 3.3.5?

**Comment by PhentomPT** [comment]
Yes i believe soo
