### ISSUE TITLE
Install error DB

### ISSUE THREAD

**Issue by wattz1979** [PhentomPT/PhentomCMS#11]
Hi Phentom still not managed to get this installed even after the last update :( 

latest error 

![screenshot_9](https://cloud.githubusercontent.com/assets/11533270/7866376/f75c801a-0566-11e5-8744-bda2de608cd4.png)

**Comment by PhentomPT** [comment]
That only happens on windows machines and i only have 1 available in the weekend to test and fix it. Thabns for the heads up!

**Comment by PhentomPT** [comment]
Probably found what's wrong. 
Inserting id in a primary auto increment field its probably not a good idea =P

**Comment by wattz1979** [comment]
Ok will keep a eye on repo for a new update to test it ;)

**Comment by PhentomPT** [comment]
I did a commit for a more detailed error detection, can u check again?

**Comment by wattz1979** [comment]
Sorry took so long i had to go out here is error from latest update

Notice: Undefined variable: con in C:\xampp\htdocs\555\install\include\db_error.php on line 72

Notice: Trying to get property of non-object in C:\xampp\htdocs\555\install\include\db_error.php on line 72
Query Error - Database Error

Your query is: INSERT INTO `menu` (`name`, `link`, `link_order`, `logged`, `position`) VALUES ('Account P', '?page=account', 2, 1, 'left'), ('Forum', '?page=forum', 4, 0, 'left'), ('Store', '?page=store', 6, 1, 'right'), ('Armory', '?page=armory', 7, 0, 'right'), ('Media', '?page=media', 8, 0, 'right'), ('Home', 'index.php', 1, 0, 'left'), ('Login', '?page=login', 3, 0, 'left'), ('Register', '?page=register', 5, 0, 'right');

**Comment by PhentomPT** [comment]
It now should be giving you the proper query error

**Comment by wattz1979** [comment]
Query Error - Database Error

Query error: Field 'icon' doesn't have a default value

Your query is: INSERT INTO `menu` (`name`, `link`, `link_order`, `logged`, `position`) VALUES ('Account P', '?page=account', 2, 1, 'left'), ('Forum', '?page=forum', 4, 0, 'left'), ('Store', '?page=store', 6, 1, 'right'), ('Armory', '?page=armory', 7, 0, 'right'), ('Media', '?page=media', 8, 0, 'right'), ('Home', 'index.php', 1, 0, 'left'), ('Login', '?page=login', 3, 0, 'left'), ('Register', '?page=register', 5, 0, 'right');

**Comment by PhentomPT** [comment]
Fixed
