### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by SunnyTheCool** [PhentomPT/PhentomCMS#13]
Hey,

I just tried to install the cms - following error: ERR_TOO_MANY_REDIRECTS

**Comment by SunnyTheCool** [comment]
Its a problem with the ssc

**Comment by PhentomPT** [comment]
In what page and step do you get this error?
Can you post a screenshot?

**Comment by SunnyTheCool** [comment]
Well i've tried it with wamp on my local machine now. It worked perfectly. Are there any php5 modules I need ? Maybe I forgot one.

**Comment by SunnyTheCool** [comment]
Ah btw: my php is version 5.4

**Comment by PhentomPT** [comment]
No extra modules needed,
Only php 5.4 or higher and permissions to the web folder.
Any other problems let me know
