### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by spuresz** [PhentomPT/PhentomCMS#15]
? - Mysql 5.4 or higher is required.
but i have 5.6.17

Install trinity v6 , warlord of draenor
First 1-2 step done, and 3. error

Query Error - Database Error

Query error: Table 'menu' already exists

Your query is: CREATE TABLE `menu` ( `id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL DEFAULT 'link name', `link` VARCHAR(50) NOT NULL DEFAULT '?page=', `link_order` INT(11) NULL DEFAULT NULL, `logged` INT(11) NOT NULL DEFAULT '0', `position` VARCHAR(50) NOT NULL DEFAULT 'left', `icon` VARCHAR(50) NOT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by spuresz** [comment]
Now fine, done install
"No errors where detected during installation! "

But have errors:
Admin panel index.php

![err3](https://cloud.githubusercontent.com/assets/13661259/9182888/40922b48-3fac-11e5-9329-a97711e459ca.png)



Menu problems:  does not work
-Tools menu 
-Modules
-Plugins
-themes
-languages
-info

Othermenu error:

![err](https://cloud.githubusercontent.com/assets/13661259/9182832/f94b56ba-3fab-11e5-972e-7443aadbb30c.png)

![err2](https://cloud.githubusercontent.com/assets/13661259/9182835/fcb78832-3fab-11e5-90a6-7ee20d94a521.png)

**Comment by PhentomPT** [comment]
In the latest version of the CMS the only pages that work in the admin (back-end) are the dashboard and the statistics, the others will be added in future versions.
That error that your having is related to non initialized variables in the class.statistics.php before the for loops

**Comment by spuresz** [comment]
Ok I see. Thank you! :)

**Comment by spuresz** [comment]
Now admin page does not write error
