### ISSUE TITLE
Trinity v6 account register problem

### ISSUE THREAD

**Issue by spuresz** [PhentomPT/PhentomCMS#16]
Create account, but just "auth/account" table.
Need create auth/battlenet_accounts for wow login

Trinitycore 6xx have account+battlenet_accounts table

**Comment by spuresz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/sql/base/auth_database.sql
For help

WoW.exe login table:

CREATE TABLE `battlenet_accounts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifier',
  `email` varchar(320) NOT NULL,
  `sha_pass_hash` varchar(64) NOT NULL DEFAULT '',
  `v` varchar(256) NOT NULL DEFAULT '',
  `s` varchar(64) NOT NULL DEFAULT '',
  `sessionKey` varchar(128) NOT NULL DEFAULT '',
  `joindate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_ip` varchar(15) NOT NULL DEFAULT '127.0.0.1',
  `failed_logins` int(10) unsigned NOT NULL DEFAULT '0',
  `locked` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `lock_country` varchar(2) NOT NULL DEFAULT '00',
  `last_login` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `online` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `locale` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `os` varchar(4) NOT NULL DEFAULT '',
  `LastCharacterUndelete` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Account System';
/*!40101 SET character_set_client = @saved_cs_client */;

But normal account table need for account_access

**Comment by spuresz** [comment]
example:

		<?php

		function Reg()
		{
			if (isset($_POST['reg'])==true) {
                     require_once('config.php'); 
				$user = $_POST['username'];
				$pass = sha1(strtoupper($user.':'.$_POST['password'])); 
				$email = $_POST['email'];

				$con = mysql_connect($dbhost, $dbuser, $dbpassword);

				if (!$con) 
 				{ 
     				die('Could not connect!'); 
  				} else {
  					mysql_select_db("$logondb", $con); 

					$sql="INSERT INTO account (username, sha_pass_hash, email) VALUES ('$user','$pass','$email')"; 
					$sql="INSERT INTO battlenet_accounts (sha_pass_hash, email) VALUES ('$pass','$email')"; 

// (just small code, example)
wow  only use battlenetaccount table for login, but account table need for account_access

Website login enough email+pass, no need username
or weblogin account table, but register battlenetaccount table   //sry for bad english :D

**Comment by spuresz** [comment]
beta!

 <?php
//Refuses direct access
if (!defined("PhentomCMS")){ exit; }

//Trinity Tables

//Auth
$account_table = 'battlenet_accounts';
$account_access = 'account_access';
$account_banned_table = 'battlenet_account_bans';
$realmlist_table = 'realmlist';
$uptime_table = 'uptime';


//Characters
$characters_table = 'characters';
$gm_tickets_table = 'gm_tickets';
$guild_table = 'guild';
$mail_table = 'mail';
$mail_items_table = 'mail_items';


//World

?> 


////

 <?php
//Refuses direct access
if (!defined("PhentomCMS")){ exit; }

$username = $_POST['username'];
$password = sha_password($username,$_POST['password']);

$mysqli -> select_db($acc_db);

$check_account = $mysqli -> query("SELECT * FROM `battlenet_accounts` WHERE email='$email' and sha_pass_hash='$password'") or die( $mysqli -> error );
$count = $check_account -> num_rows;
 
if ($count > 0){
    $_SESSION['username'] = $username;
    header("Location: index.php");
}
else{
    echo "<div class='fail'>Wrong User/Password</div>";
}
?> 


/////


 <?php
//Refuse direct access
if(!defined("PhentomCMS")){ exit; }

if (isset($_POST['remail']) and isset($_POST['rpassword'])){
    if ($_POST['rpassword'] == $_POST['vpassword']){
        $email = $_POST['remail'];
        $password = sha_password($email,$_POST['rpassword']);
        
        $mysqli -> select_db($acc_db);
        $check = $mysqli -> query("SELECT id FROM `battlenet_accounts` WHERE email='$email'") or die($mysqli -> error); 
        $count = $check -> num_rows;
        
        if ($count > 0){
            echo "<p class='fail'>Username already exists.</p>";
        }
        else{ 
            $mysqli -> query("INSERT INTO `battlenet_accounts` (email, sha_pass_hash) VALUES ('$email', '$password')") or die($mysqli -> error);
            header("Location: ?page=register_success");
        }
    }
    else{
        echo "<p class='fail'>Password missmatch.</p>";
    }
}

**Comment by PhentomPT** [comment]
Check the changes in class.account.php

**Comment by spuresz** [comment]
Yes, now it works perfectly!
Nice work! :)

**Comment by PhentomPT** [comment]
No problem! Enjoy
