### ISSUE TITLE
forum error

### ISSUE THREAD

**Issue by spuresz** [PhentomPT/PhentomCMS#17]
login error

( ! ) Warning: include(C:\wamp\www\Phentom\forum/include/page.php): failed to open stream: No such file or directory in C:\wamp\www\Phentom\forum\index.php on line 57
Call Stack
#	Time	Memory	Function	Location
1	0.0000	260320	{main}( )	..\index.php:0

( ! ) Warning: include(): Failed opening 'C:\wamp\www\Phentom\forum/include/page.php' for inclusion (include_path='.;C:\php\pear') in C:\wamp\www\Phentom\forum\index.php on line 57
Call Stack
#	Time	Memory	Function	Location
1	0.0000	260320	{main}( )	..\index.php:0

**Comment by PhentomPT** [comment]
The forum app is a very premature feature added and i'm not giving support for it until the website is done.
Thanks for the error report.

**Comment by spuresz** [comment]
All right, thank you for your answer! :)
