### ISSUE TITLE
index page

### ISSUE THREAD

**Issue by spuresz** [PhentomPT/PhentomCMS#18]
![error4](https://cloud.githubusercontent.com/assets/13661259/9250182/4e2ea3fa-41cb-11e5-9a9b-9182b5a632e1.png)

**Comment by PhentomPT** [comment]
Try change your class.statistics.php changing the function saveStatistics() to this:

public function saveStatistics(){
		$your_session = $this->getSessionID();
		
		$get_session = $this->db->SimpleQuery("SELECT * FROM ". DBNAME .".". WEB_TBL_STATISTICS ." WHERE session='$your_session'");
		
		if (count($get_session) < 1){
			$this->db->SimpleQuery("INSERT INTO ". DBNAME .".". WEB_TBL_STATISTICS ." (session,ip,country,state,town) VALUES ('$your_session','$this->ip','".$this->locations['country']."','".$this->locations['state']."','".$this->locations['town']."')");
		}
	}

**Comment by spuresz** [comment]
I changed

The problem is still there, but only when you first open the web page. Then 2-3x f5 page and disappear error ( do not show)
