### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by MrBricky** [PhentomPT/PhentomCMS#21]
I just tried to install PhentomCMS on vps Linux.

**Comment by PhentomPT** [comment]
what kind of link are you using? 
Ex: sub.domain.com or domain.com

**Comment by MrBricky** [comment]
domain.com

**Comment by PhentomPT** [comment]
Does it work out of the vpn?

**Comment by MrBricky** [comment]
Yeah. Just It doesn't work on my linux server.

**Comment by MrBricky** [comment]
I think There is one option. I have to configure manually website.
Just tell me what files I have set up for proper installation.

**Comment by MrBricky** [comment]
<a href="http://pl.tinypic.com?ref=4to5t4" target="_blank"><img src="http://i61.tinypic.com/4to5t4.png" border="0" alt="Image and video hosting by TinyPic"></a>

Bug
Found on my PC

**Comment by PhentomPT** [comment]
still need help configuring it manually?

**Comment by MrBricky** [comment]
Yeah, tell me what files I have set up for proper installation.

**Comment by PhentomPT** [comment]
Open the config.php file inside each application and add this to the end ( fill with your database information )

<pre>
//DB constants
define("DBHOST", "127.0.0.1");
define("DBUSER", "root");
define("DBPASS", "root");
define("DBNAME", "website");
define("DBFORUM", "forum");
define("DBPORT", "3306");
</pre>

Run this sql code, and after that insert a row in the table 'info' with your server information:

<pre>
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.0.20-MariaDB - MariaDB Server
-- Server OS:                    Linux
-- HeidiSQL Version:             9.1.0.4867
-- --------------------------------------------------------
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
-- Dumping database structure for website
DROP DATABASE IF EXISTS `website`;
CREATE DATABASE IF NOT EXISTS `website` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `website`;
-- Dumping structure for table website.account_info
DROP TABLE IF EXISTS `account_info`;
CREATE TABLE IF NOT EXISTS `account_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `vote_points` int(11) NOT NULL DEFAULT '0',
  `donation_points` int(11) NOT NULL DEFAULT '0',
  `avatar` varchar(50) NOT NULL DEFAULT 'default.png',
  `rank` int(11) NOT NULL DEFAULT '0',
  `special` varchar(50) NOT NULL DEFAULT '0',
  `join_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Dumping data for table website.account_info: ~0 rows (approximately)
/*!40000 ALTER TABLE `account_info` DISABLE KEYS */;
/*!40000 ALTER TABLE `account_info` ENABLE KEYS */;
-- Dumping structure for table website.chat
DROP TABLE IF EXISTS `chat`;
CREATE TABLE IF NOT EXISTS `chat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` varchar(50) DEFAULT NULL,
  `msg` text,
  `posttime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Dumping data for table website.chat: ~0 rows (approximately)
/*!40000 ALTER TABLE `chat` DISABLE KEYS */;
/*!40000 ALTER TABLE `chat` ENABLE KEYS */;
-- Dumping structure for table website.info
DROP TABLE IF EXISTS `info`;
CREATE TABLE IF NOT EXISTS `info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) NOT NULL DEFAULT 'teste',
  `slogan` varchar(100) NOT NULL DEFAULT 'teste123',
  `core` varchar(50) NOT NULL DEFAULT 'trinity',
  `expansion` int(11) NOT NULL DEFAULT '0',
  `acc_db` varchar(50) NOT NULL DEFAULT 'auth',
  `char_db` varchar(50) NOT NULL DEFAULT 'characters',
  `world_db` varchar(50) NOT NULL DEFAULT 'world',
  `style` varchar(50) NOT NULL DEFAULT 'default',
  `onplayers` int(11) NOT NULL DEFAULT '200',
  `slider` varchar(50) NOT NULL DEFAULT 'on',
  `realmlist` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Dumping data for table website.info: ~0 rows (approximately)
/*!40000 ALTER TABLE `info` DISABLE KEYS */;
/*!40000 ALTER TABLE `info` ENABLE KEYS */;
-- Dumping structure for table website.menu
DROP TABLE IF EXISTS `menu`;
CREATE TABLE IF NOT EXISTS `menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT 'link name',
  `link` varchar(50) NOT NULL DEFAULT '?page=',
  `link_order` int(11) DEFAULT NULL,
  `logged` int(11) NOT NULL DEFAULT '0',
  `position` varchar(50) NOT NULL DEFAULT 'left',
  `icon` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
-- Dumping data for table website.menu: ~8 rows (approximately)
/*!40000 ALTER TABLE `menu` DISABLE KEYS */;
REPLACE INTO `menu` (`id`, `name`, `link`, `link_order`, `logged`, `position`, `icon`) VALUES
    (1, 'Account P', '?page=account', 2, 1, 'left', ''),
    (2, 'Forum', '?page=forum', 4, 0, 'left', ''),
    (3, 'Store', '?page=store', 6, 1, 'right', ''),
    (4, 'Armory', '?page=armory', 7, 0, 'right', ''),
    (5, 'Media', '?page=media', 8, 0, 'right', ''),
    (6, 'Home', 'index.php', 1, 0, 'left', ''),
    (7, 'Login', '?page=login', 3, 0, 'left', ''),
    (8, 'Register', '?page=register', 5, 0, 'right', '');
/*!40000 ALTER TABLE `menu` ENABLE KEYS */;
-- Dumping structure for table website.news
DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) NOT NULL DEFAULT 'Announcement',
  `user` varchar(50) DEFAULT NULL,
  `content` text NOT NULL,
  `media` varchar(50) NOT NULL DEFAULT 'news.jpg',
  `posttime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
-- Dumping data for table website.news: ~0 rows (approximately)
/*!40000 ALTER TABLE `news` DISABLE KEYS */;
REPLACE INTO `news` (`id`, `title`, `user`, `content`, `media`, `posttime`) VALUES
    (1, 'Announcement', '1', 'Welcome to PhentomCMS', 'news.jpg', '2015-08-25 13:51:50');
/*!40000 ALTER TABLE `news` ENABLE KEYS */;
-- Dumping structure for table website.statistics
DROP TABLE IF EXISTS `statistics`;
CREATE TABLE IF NOT EXISTS `statistics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` char(100) DEFAULT NULL,
  `ip` char(20) DEFAULT NULL,
  `country` char(20) DEFAULT NULL,
  `state` char(20) DEFAULT NULL,
  `town` char(20) DEFAULT NULL,
  `last_seen` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Dumping data for table website.statistics: ~0 rows (approximately)
/*!40000 ALTER TABLE `statistics` DISABLE KEYS */;
/*!40000 ALTER TABLE `statistics` ENABLE KEYS */;
-- Dumping structure for table website.voted_cooldown
DROP TABLE IF EXISTS `voted_cooldown`;
CREATE TABLE IF NOT EXISTS `voted_cooldown` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL DEFAULT '0',
  `vote_link_id` int(11) NOT NULL DEFAULT '0',
  `voted` int(11) NOT NULL DEFAULT '0',
  `voted_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Dumping data for table website.voted_cooldown: ~0 rows (approximately)
/*!40000 ALTER TABLE `voted_cooldown` DISABLE KEYS */;
/*!40000 ALTER TABLE `voted_cooldown` ENABLE KEYS */;
-- Dumping structure for table website.vote_links
DROP TABLE IF EXISTS `vote_links`;
CREATE TABLE IF NOT EXISTS `vote_links` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `vote_link` varchar(50) DEFAULT NULL,
  `vote_img` varchar(50) DEFAULT NULL,
  `value` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- Dumping data for table website.vote_links: ~0 rows (approximately)
/*!40000 ALTER TABLE `vote_links` DISABLE KEYS */;
/*!40000 ALTER TABLE `vote_links` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
</pre>

**Comment by MrBricky** [comment]
Thanks

**Comment by PhentomPT** [comment]
Tell me if you run into any problems with that, or if all went right

**Comment by MrBricky** [comment]
It didn't work
I see clean site without any errors

**Comment by PhentomPT** [comment]
what is not working?
detail please

**Comment by MrBricky** [comment]
Everything.
I just see white clean website without any errors.

**Comment by PhentomPT** [comment]
Did you delete the install folder?
Did you add a row of information to the table info with your server information?

**Comment by MrBricky** [comment]
Yes I did

**Comment by PhentomPT** [comment]
do you have a folder named trash in the same place?
