### ISSUE TITLE
please continue the cms

### ISSUE THREAD

**Issue by tiikerikissa** [PhentomPT/PhentomCMS#4]
please continue the cms

**Comment by PhentomPT** [comment]
I'm working on it! 
Here are some quick previews

![admin_mobile_phentom_cms](https://cloud.githubusercontent.com/assets/8815300/6751992/4cca9b18-cf02-11e4-91c7-a40a72678477.png)
![forum_mobile_phentom_cms](https://cloud.githubusercontent.com/assets/8815300/6751990/4cc8b4ba-cf02-11e4-91b7-cffe355ca3d8.png)
![forum_phentom_cms](https://cloud.githubusercontent.com/assets/8815300/6751993/4ccaaf22-cf02-11e4-8d0d-3a619f87b038.png)
![install_phentom_cms](https://cloud.githubusercontent.com/assets/8815300/6751994/4ccba29c-cf02-11e4-81ce-87b5f8eff1b8.png)
![website_phentom_cms](https://cloud.githubusercontent.com/assets/8815300/6751991/4cc9222e-cf02-11e4-8886-eb066ad03e95.png)

**Comment by tiikerikissa** [comment]
okey :) i like this cms this is best

**Comment by PhentomPT** [comment]
Thanks for all the support! Really appreciate it =)
