### ISSUE TITLE
Errors when trying to install

### ISSUE THREAD

**Issue by wowferreira** [PhentomPT/PhentomCMS#6]
Hello Phentom. I have these errors whenever I try to install the theme:

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 8

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBUSER - assumed 'DBUSER' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPASS - assumed 'DBPASS' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBNAME - assumed 'DBNAME' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPORT - assumed 'DBPORT' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Warning: include(C:\xampp\htdocs\PhentomCMS\install/language/english/general.php): failed to open stream: No such file or directory in C:\xampp\htdocs\PhentomCMS\install\index.php on line 31

Warning: include(): Failed opening 'C:\xampp\htdocs\PhentomCMS\install/language/english/general.php' for inclusion (include_path='.;\xampp\php\PEAR') in C:\xampp\htdocs\PhentomCMS\install\index.php on line 31

Warning: include(C:\xampp\htdocs\PhentomCMS\install/language/english/install.php): failed to open stream: No such file or directory in C:\xampp\htdocs\PhentomCMS\install\controller\preload.php on line 7

Warning: include(): Failed opening 'C:\xampp\htdocs\PhentomCMS\install/language/english/install.php' for inclusion (include_path='.;\xampp\php\PEAR') in C:\xampp\htdocs\PhentomCMS\install\controller\preload.php on line 7

Notice: Undefined index: welcome in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 54

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 54

Notice: Undefined index: welcome_txt in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 57

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 57

Notice: Undefined index: welcome_np in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 61

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 61

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 8

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBUSER - assumed 'DBUSER' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPASS - assumed 'DBPASS' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBNAME - assumed 'DBNAME' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPORT - assumed 'DBPORT' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

 
Notice: Undefined index: db_info in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 36

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 36

Notice: Undefined index: db_host in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 46

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 46

Notice: Undefined index: db_user in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 57

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 57

Notice: Undefined index: db_password in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 68

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 68

Notice: Undefined index: db_name in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 79

Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 79

**Comment by tkrokli** [comment]
Just to make it easier to compare your error message lines, I added 3 "back ticks" ( ``` ) above the error text and removed the blank lines between the error lines :
```
Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 8
Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBUSER - assumed 'DBUSER' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBPASS - assumed 'DBPASS' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBNAME - assumed 'DBNAME' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBPORT - assumed 'DBPORT' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Warning: mysqli::mysqli() expects parameter 5 to be long, string given in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Warning: include(C:\xampp\htdocs\PhentomCMS\install/language/english/general.php): failed to open stream: No such file or directory in C:\xampp\htdocs\PhentomCMS\install\index.php on line 31
Warning: include(): Failed opening 'C:\xampp\htdocs\PhentomCMS\install/language/english/general.php' for inclusion (include_path='.;\xampp\php\PEAR') in C:\xampp\htdocs\PhentomCMS\install\index.php on line 31
Warning: include(C:\xampp\htdocs\PhentomCMS\install/language/english/install.php): failed to open stream: No such file or directory in C:\xampp\htdocs\PhentomCMS\install\controller\preload.php on line 7
Warning: include(): Failed opening 'C:\xampp\htdocs\PhentomCMS\install/language/english/install.php' for inclusion (include_path='.;\xampp\php\PEAR') in C:\xampp\htdocs\PhentomCMS\install\controller\preload.php on line 7
Notice: Undefined index: welcome in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 54
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 54
Notice: Undefined index: welcome_txt in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 57
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 57
Notice: Undefined index: welcome_np in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 61
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\0b0978aa9baf886c4a6a7ad8969372cb42f5e8f9.file.header.html.php on line 61
Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 8
Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBUSER - assumed 'DBUSER' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBPASS - assumed 'DBPASS' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBNAME - assumed 'DBNAME' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Use of undefined constant DBPORT - assumed 'DBPORT' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Warning: mysqli::mysqli() expects parameter 5 to be long, string given in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9
Notice: Undefined index: db_info in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 36
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 36
Notice: Undefined index: db_host in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 46
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 46
Notice: Undefined index: db_user in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 57
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 57
Notice: Undefined index: db_password in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 68
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 68
Notice: Undefined index: db_name in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 79
Notice: Trying to get property of non-object in C:\xampp\htdocs\PhentomCMS\install\templates_c\c3c875bf895084728b9d091e4568c7bea4652af7.file.db_info.html.php on line 79

**Comment by PhentomPT** [comment]
´whenever I try to install the theme´ ?
how did you installation process went?

**Comment by wowferreira** [comment]
When I open the page, I get those errors. I'll try it again now.

**Comment by wowferreira** [comment]
Ok, I'm trying to install the CMS, but I still have these errors:

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 8

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBUSER - assumed 'DBUSER' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPASS - assumed 'DBPASS' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBNAME - assumed 'DBNAME' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPORT - assumed 'DBPORT' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 8

Notice: Use of undefined constant DBHOST - assumed 'DBHOST' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBUSER - assumed 'DBUSER' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPASS - assumed 'DBPASS' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBNAME - assumed 'DBNAME' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Notice: Use of undefined constant DBPORT - assumed 'DBPORT' in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

Warning: mysqli::mysqli() expects parameter 5 to be long, string given in C:\xampp\htdocs\PhentomCMS\core\model\class.database.php on line 9

**Comment by PhentomPT** [comment]
The error your having is that after you entered the DB information, the config.php is suppose to store the configuration and its apparently not.
Did you give permissions to the CMS folder? (This may cause the problem to occur).

**Comment by wowferreira** [comment]
No. I put the cms on my htdocs, I open 127.0.0.1 and I get all these errors.

**Comment by PhentomPT** [comment]
Then you should give permissions to the folder even before starting the installation

**Comment by wowferreira** [comment]
What you mean?

**Comment by tkrokli** [comment]
> at 2015-04-23, 19:33 UTC, @wowferreira wrote:
What you mean?

He means that you need to set the correct user permissions (file access) for the folder (and  files)
where you keep the CMS installed, *before* you start installing the CMS.
