### ISSUE TITLE
website wont show after install

### ISSUE THREAD

**Issue by epicwowserver** [PhentomPT/PhentomCMS#7]
After installing the website doesnt show up, its just a blank page

**Comment by epicwowserver** [comment]
ok the website decided to show now i get this on register

Query Error - Database Error
Your query is: SELECT id,email as username FROM battlenet_accounts ORDER BY id DESC LIMIT 1

**Comment by PhentomPT** [comment]
I'll run some tests and check on that.
Do you have any details on the blank page after your installation?

**Comment by epicwowserver** [comment]
nothing shows, i have tried everything
