### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by adriancs35** [PhentomPT/PhentomCMS#8]
I tried to install it and I can't get the scripts to load on XAMPP@Windows
http://gyazo.com/7f15a92fe95f1f8af5a2118d67048104
My webserver works because I can run other php scripts, it's not the cookies tried to clear them and tried to use another browser. 
I believe it's from the install script.

**Comment by PhentomPT** [comment]
How or when in the installation process (if you even saw it) did you get to that page?
Did you give permission to the website before starting?
If you have any additional information let me know.

**Comment by adriancs35** [comment]
Hm, I did not even got to it, to problem comes right when im trying to get on the website.
Permissions? I thought the 777 thing is only on linux?

**Comment by PhentomPT** [comment]
I think you need to give permissions on windows to, since the smarty template engine will need to create files/folders on the project

**Comment by PhentomPT** [comment]
I will commit an update with some changes including some installation fixes

**Comment by adriancs35** [comment]
I still have this problem even after the commit, checked the permissions are all good.

**Comment by PhentomPT** [comment]
How can you confirm its from the install directory?

**Comment by adriancs35** [comment]
I changed the name of install folder into install2 so I can get through index.php redirect, it redirected me to website directory where it gave me php errors of unwrited variables (because i didnt ran install)
http://gyazo.com/f5dfd8c535246d21bedda8a20bb8a621

**Comment by PhentomPT** [comment]
And when you have the install folder the page don't redirect you?
Try to go directly to localhost/install

**Comment by adriancs35** [comment]
The redirect works as it should, also tried that the problem is in /install.

**Comment by PhentomPT** [comment]
Just to be clear, you can't view the install?
