### ISSUE TITLE
Install Bugs

### ISSUE THREAD

**Issue by wattz1979** [PhentomPT/PhentomCMS#9]
Hi Phentom , thought i would install this to give it a try but seems the install is buggy and doesnt want to work ,added two screengrabs of the errors on the first two pages below 

http://s8.postimg.org/6k8ysd6xh/Screenshot_6.png

http://s23.postimg.org/p5hb6t3uj/Screenshot_7.png

**Comment by PhentomPT** [comment]
Hey, did you give permissions to the website before starting the installation?
The second screenshot its because the config file got installed to many time.
Try  to download a fresh copy and give permissions to the website.

Let me know how it went.

**Comment by wattz1979** [comment]
Hi Phentom ,thanks for the reply ,which folders am changing permissions on ? i couldn't find nothing in the readme regarding file permissions

**Comment by PhentomPT** [comment]
After copying the fresh copy of the website folder to you web server folder you have to give permissions
Windows?
- explorer -> go to the folder -> right-click (folders/files) -> permissions -> read/write (something like this)
Linux?
- terminal -> $ sudo chmod 755 -R /var/www/html/YourFolderName

**Comment by wattz1979** [comment]
yeh i am using windows and the permissions were fine for the site folder, but to test what you are saying i have now allowed all so the entire folder is the equivilant of cmod 777 (all readable and writable) and still the same issue persists ,are there any extra php extensions i need to enable in my php.ini ?

**Comment by PhentomPT** [comment]
I think not, the permissions are because of Smarty template engine, but no extra php extensions are necessary.
That error pops up on the first page of the installation?

**Comment by wattz1979** [comment]
yeh on the first install page and after 

http://prntscr.com/6zhm6g

**Comment by PhentomPT** [comment]
Check the config.php in the install folder and tell me if you have this constants:
DBHOST
DBUSER
DBPASS
DBNAME
BDPORT

If you do, they should not be there in the first page of the installation.

**Comment by wattz1979** [comment]
ok ,in the install folder only config.php i can see is in the install/core ,contents of the file are as below

<?php
//Refuses direct access
if (!defined("SSC")){ exit("You don't have access to this file"); }

//Stats session
session_start();

//System constants
define("DIR", dirname(__DIR__));
define("WEB_PATH", dirname(DIR)); //This is the primary path of the system
define("CONTROLLER_PATH", DIR ."/controller");
define("VIEW_PATH", DIR ."/view");
define("CORE_PATH", DIR ."/core");
define("PLUGIN_PATH", DIR ."/plugin");
define("SCRIPT_PATH", DIR ."/script");
define("STYLE_PATH", DIR ."/style");
define("LANGUAGE_PATH", DIR ."/language");
define("IMAGE_PATH", DIR ."/image");
define("INCLUDE_PATH", DIR ."/include");

**Comment by PhentomPT** [comment]
That's correct and its a very strange error since they don't exist the class.database.php should not even call for them

**Comment by wattz1979** [comment]
the error is stopping the cms being installed ,i can put info in at the bottom of the first page but second page is messed right up leaving it uninstallable 
http://prntscr.com/6zhvfk

**Comment by wattz1979** [comment]
shouldnt the <?php have closing at the bottom of these with ?>

**Comment by PhentomPT** [comment]
I will commit an update with some changes including some installation fixes

**Comment by wattz1979** [comment]
ok thank you Phentom greatly appreciated ,i will check back when i can ;)

**Comment by wattz1979** [comment]
Hi Phentom any update on this issue ? ,i just redownload and tried to install again and still same on page 2 

http://prntscr.com/71n3e4

**Comment by PhentomPT** [comment]
I tried to identify why that happens but i can't find any solution, that errors are Smarty related

**Comment by PhentomPT** [comment]
Fixed, sorry it took so long
